/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jPack_Interfaz;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AlmidonTapia
 */
public class jFrame_Pizzeria extends javax.swing.JFrame {
    
    /*
    *inicializar fecha
    jLabel_DatosFecha
     * Creates new form jFrame_Pizzeria
     */
    private List<String> NumeroPedidos;
    private List<String> Nombres;
    private List<String> Apellidos;
    private List<String> Ingredientes;
    private List<String> Tamanos;
    private List<Double> Totales;  // Lista para almacenar los totales de cada pedido
    private int pedidoCounter;
    
    public jFrame_Pizzeria() {  
        
        initComponents();
        jTextField_NumeroCliente.setVisible(false);
        NumeroPedidos = new ArrayList<>();
        Nombres = new ArrayList<>();
        Apellidos = new ArrayList<>();
        Ingredientes = new ArrayList<>();
        Tamanos = new ArrayList<>();
        Totales = new ArrayList<>();
        pedidoCounter = 1;

        DefaultTableModel model = new DefaultTableModel();
        jTable_Pedido.setModel(model);
        model.addColumn("N°");
        model.addColumn("Nombres");
        model.addColumn("Apellidos");
        model.addColumn("Ingredientes");
        model.addColumn("Tamaño");
        model.addColumn("Totales");
       
        actualizarFecha();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_TamañosPizza = new javax.swing.ButtonGroup();
        jPanel_font = new javax.swing.JPanel();
        jLabel_NombrePizzeria = new javax.swing.JLabel();
        jLabel_IconPizzeria = new javax.swing.JLabel();
        jPanel_DatosCliente = new javax.swing.JPanel();
        jTextField_InputNombre = new javax.swing.JTextField();
        jLabel_NombreCliente = new javax.swing.JLabel();
        jLabel_ApellidoCliente = new javax.swing.JLabel();
        jTextField_InputApellido = new javax.swing.JTextField();
        jButton_LimpiarDatos = new javax.swing.JButton();
        jLabel_NumeroCliente = new javax.swing.JLabel();
        jTextField_NumeroCliente = new javax.swing.JTextField();
        jPanel_Pedido = new javax.swing.JPanel();
        jPanel_IngredientesPizza = new javax.swing.JPanel();
        jCheckBox_Ingrediente1 = new javax.swing.JCheckBox();
        jCheckBox_Ingrediente2 = new javax.swing.JCheckBox();
        jCheckBox_Ingrediente3 = new javax.swing.JCheckBox();
        jCheckBox_Ingrediente4 = new javax.swing.JCheckBox();
        jPanel_TamañoPizza = new javax.swing.JPanel();
        jRadioButton_Tamaño1 = new javax.swing.JRadioButton();
        jRadioButton_Tamaño2 = new javax.swing.JRadioButton();
        jRadioButton_Tamaño3 = new javax.swing.JRadioButton();
        jButton_AgregarPedido = new javax.swing.JButton();
        jPanel_DetallesPedido = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Pedido = new javax.swing.JTable();
        jLabel_Total = new javax.swing.JLabel();
        jButton_GuardarPedido = new javax.swing.JButton();
        jButton_EliminarPedido = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();
        jLabel_MontoTotal = new javax.swing.JLabel();
        jLabel_DatosFecha = new javax.swing.JLabel();
        jLabel_Fecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venta");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_font.setBackground(new java.awt.Color(43, 43, 43));
        jPanel_font.setForeground(new java.awt.Color(43, 43, 43));
        jPanel_font.setToolTipText("");
        jPanel_font.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NombrePizzeria.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_NombrePizzeria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_NombrePizzeria.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NombrePizzeria.setText("PIZZERIA NAPOLI");
        jPanel_font.add(jLabel_NombrePizzeria, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 190, -1));

        jLabel_IconPizzeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/nav-logo (3).png"))); // NOI18N
        jPanel_font.add(jLabel_IconPizzeria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 70, 60));
        jLabel_IconPizzeria.getAccessibleContext().setAccessibleName("jLabel_IconPizzeria");

        jPanel_DatosCliente.setBackground(new java.awt.Color(43, 43, 43));
        jPanel_DatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel_DatosCliente.setForeground(new java.awt.Color(43, 43, 43));

        jTextField_InputNombre.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_InputNombre.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_NombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NombreCliente.setText("Nombre:");

        jLabel_ApellidoCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ApellidoCliente.setText("Apellidos");

        jTextField_InputApellido.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_InputApellido.setForeground(new java.awt.Color(255, 255, 255));

        jButton_LimpiarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/escoba.png"))); // NOI18N
        jButton_LimpiarDatos.setText("Limpiar Campos");
        jButton_LimpiarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LimpiarDatosActionPerformed(evt);
            }
        });

        jLabel_NumeroCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NumeroCliente.setText("N° Orden");

        jTextField_NumeroCliente.setEditable(false);
        jTextField_NumeroCliente.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_NumeroCliente.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel_DatosClienteLayout = new javax.swing.GroupLayout(jPanel_DatosCliente);
        jPanel_DatosCliente.setLayout(jPanel_DatosClienteLayout);
        jPanel_DatosClienteLayout.setHorizontalGroup(
            jPanel_DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_DatosClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_DatosClienteLayout.createSequentialGroup()
                        .addComponent(jLabel_ApellidoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_LimpiarDatos)
                            .addComponent(jTextField_InputApellido)))
                    .addGroup(jPanel_DatosClienteLayout.createSequentialGroup()
                        .addGroup(jPanel_DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_NombreCliente)
                            .addComponent(jLabel_NumeroCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_NumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_InputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42))
        );
        jPanel_DatosClienteLayout.setVerticalGroup(
            jPanel_DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DatosClienteLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel_DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_NumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_NumeroCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel_DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_NombreCliente)
                    .addComponent(jTextField_InputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_InputApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ApellidoCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_LimpiarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_font.add(jPanel_DatosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 102, 260, -1));

        jPanel_Pedido.setBackground(new java.awt.Color(43, 43, 43));
        jPanel_Pedido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalles pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel_Pedido.setForeground(new java.awt.Color(43, 43, 43));

        jPanel_IngredientesPizza.setBackground(new java.awt.Color(43, 43, 43));
        jPanel_IngredientesPizza.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingredientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel_IngredientesPizza.setForeground(new java.awt.Color(43, 43, 43));

        jCheckBox_Ingrediente1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_Ingrediente1.setText("Bacon");

        jCheckBox_Ingrediente2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_Ingrediente2.setText("Anchoas");
        jCheckBox_Ingrediente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_Ingrediente2ActionPerformed(evt);
            }
        });

        jCheckBox_Ingrediente3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_Ingrediente3.setText("Cebolla");

        jCheckBox_Ingrediente4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_Ingrediente4.setText("Pimenton");

        javax.swing.GroupLayout jPanel_IngredientesPizzaLayout = new javax.swing.GroupLayout(jPanel_IngredientesPizza);
        jPanel_IngredientesPizza.setLayout(jPanel_IngredientesPizzaLayout);
        jPanel_IngredientesPizzaLayout.setHorizontalGroup(
            jPanel_IngredientesPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_IngredientesPizzaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel_IngredientesPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_Ingrediente1)
                    .addComponent(jCheckBox_Ingrediente2)
                    .addComponent(jCheckBox_Ingrediente3)
                    .addComponent(jCheckBox_Ingrediente4))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel_IngredientesPizzaLayout.setVerticalGroup(
            jPanel_IngredientesPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_IngredientesPizzaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox_Ingrediente1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_Ingrediente2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_Ingrediente3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_Ingrediente4)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel_TamañoPizza.setBackground(new java.awt.Color(43, 43, 43));
        jPanel_TamañoPizza.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tamaño", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel_TamañoPizza.setForeground(new java.awt.Color(43, 43, 43));

        buttonGroup_TamañosPizza.add(jRadioButton_Tamaño1);
        jRadioButton_Tamaño1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_Tamaño1.setText("Pequeña");

        buttonGroup_TamañosPizza.add(jRadioButton_Tamaño2);
        jRadioButton_Tamaño2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_Tamaño2.setText("Mediana");

        buttonGroup_TamañosPizza.add(jRadioButton_Tamaño3);
        jRadioButton_Tamaño3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_Tamaño3.setSelected(true);
        jRadioButton_Tamaño3.setText("Familiar");

        javax.swing.GroupLayout jPanel_TamañoPizzaLayout = new javax.swing.GroupLayout(jPanel_TamañoPizza);
        jPanel_TamañoPizza.setLayout(jPanel_TamañoPizzaLayout);
        jPanel_TamañoPizzaLayout.setHorizontalGroup(
            jPanel_TamañoPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TamañoPizzaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_TamañoPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_Tamaño1)
                    .addComponent(jRadioButton_Tamaño2)
                    .addComponent(jRadioButton_Tamaño3))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel_TamañoPizzaLayout.setVerticalGroup(
            jPanel_TamañoPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TamañoPizzaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton_Tamaño1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_Tamaño2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_Tamaño3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_AgregarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/boton-agregar.png"))); // NOI18N
        jButton_AgregarPedido.setText("Agregar Pedido");
        jButton_AgregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AgregarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_PedidoLayout = new javax.swing.GroupLayout(jPanel_Pedido);
        jPanel_Pedido.setLayout(jPanel_PedidoLayout);
        jPanel_PedidoLayout.setHorizontalGroup(
            jPanel_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PedidoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel_IngredientesPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_TamañoPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_PedidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_AgregarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel_PedidoLayout.setVerticalGroup(
            jPanel_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_IngredientesPizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_TamañoPizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_AgregarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_font.add(jPanel_Pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 102, 360, -1));

        jPanel_DetallesPedido.setBackground(new java.awt.Color(43, 43, 43));
        jPanel_DetallesPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel_DetallesPedido.setForeground(new java.awt.Color(43, 43, 43));

        jTable_Pedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable_Pedido);

        javax.swing.GroupLayout jPanel_DetallesPedidoLayout = new javax.swing.GroupLayout(jPanel_DetallesPedido);
        jPanel_DetallesPedido.setLayout(jPanel_DetallesPedidoLayout);
        jPanel_DetallesPedidoLayout.setHorizontalGroup(
            jPanel_DetallesPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(jPanel_DetallesPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_DetallesPedidoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel_DetallesPedidoLayout.setVerticalGroup(
            jPanel_DetallesPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
            .addGroup(jPanel_DetallesPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_DetallesPedidoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel_font.add(jPanel_DetallesPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 334, 660, 180));

        jLabel_Total.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Total.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Total.setText("Total Ingresos:");
        jPanel_font.add(jLabel_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, -1, 30));

        jButton_GuardarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/guardar-el-archivo.png"))); // NOI18N
        jButton_GuardarPedido.setText("Guardar");
        jPanel_font.add(jButton_GuardarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, -1, 30));

        jButton_EliminarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/basura.png"))); // NOI18N
        jButton_EliminarPedido.setText("Eliminar");
        jButton_EliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarPedidoActionPerformed(evt);
            }
        });
        jPanel_font.add(jButton_EliminarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, -1, 30));

        jButton_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/salida-de-emergencia.png"))); // NOI18N
        jButton_Salir.setText("Salir");
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });
        jPanel_font.add(jButton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, -1, 30));

        jLabel_MontoTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_MontoTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_MontoTotal.setText("******");
        jLabel_MontoTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel_font.add(jLabel_MontoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, 60, -1));

        jLabel_DatosFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_DatosFecha.setForeground(new java.awt.Color(0, 102, 255));
        jPanel_font.add(jLabel_DatosFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 110, 20));

        jLabel_Fecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_Fecha.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Fecha.setText("Fecha:");
        jPanel_font.add(jLabel_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        getContentPane().add(jPanel_font, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents
       private void actualizarFecha() {
        String fechaActual = obtenerFechaActual();
        jLabel_DatosFecha.setText(fechaActual);
        
    }

    private String obtenerFechaActual() {
        LocalDateTime fecha = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        return fecha.format(formatter);
    }
    private void jCheckBox_Ingrediente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_Ingrediente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_Ingrediente2ActionPerformed

    private void jButton_LimpiarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LimpiarDatosActionPerformed
        // TODO add your handling code here:
        jTextField_InputNombre.setText("");
        jTextField_InputApellido.setText("");
        jCheckBox_Ingrediente1.setSelected(false);
        jCheckBox_Ingrediente2.setSelected(false);
        jCheckBox_Ingrediente3.setSelected(false);
        jCheckBox_Ingrediente4.setSelected(false);
        jTextField_InputNombre.requestFocus();
        //buttonGroup_TamañosPizza.clearSelection();

        jButton_GuardarPedido.setEnabled(false);
        jButton_EliminarPedido.setEnabled(false);
        jButton_AgregarPedido.setEnabled(true);

    }//GEN-LAST:event_jButton_LimpiarDatosActionPerformed

    private void jButton_AgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AgregarPedidoActionPerformed
        String NPedido = String.valueOf(pedidoCounter); // Asignamos el valor del contador
        String Nombre = jTextField_InputNombre.getText();
        String Apellido = jTextField_InputApellido.getText();
        String Ingrediente = "";
        String TamanoPizza = "";
        Double Total = 0.0;

        if (Nombre.isEmpty() || Apellido.isEmpty() || (!jRadioButton_Tamaño1.isSelected() && !jRadioButton_Tamaño2.isSelected() && !jRadioButton_Tamaño3.isSelected())) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (jCheckBox_Ingrediente1.isSelected()) {
            Ingrediente += "Bacon ";
            Total += 1.5;
        }
        if (jCheckBox_Ingrediente2.isSelected()) {
            Ingrediente += "Anchoas ";
            Total += 1.80;
        }
        if (jCheckBox_Ingrediente3.isSelected()) {
            Ingrediente += "Cebolla ";
            Total += 1.0;
        }
        if (jCheckBox_Ingrediente4.isSelected()) {
            Ingrediente += "Pimenton ";
            Total += 1.2;
        }

        if (jRadioButton_Tamaño1.isSelected()) {
            TamanoPizza = "Pequeño";
            Total += 15.0;
        } else if (jRadioButton_Tamaño2.isSelected()) {
            TamanoPizza = "Mediano";
            Total += 30.0;
        } else if (jRadioButton_Tamaño3.isSelected()) {
            TamanoPizza = "Familiar";
            Total += 45.0;
        }

        NumeroPedidos.add(NPedido);
        Nombres.add(Nombre);
        Apellidos.add(Apellido);
        Ingredientes.add(Ingrediente.trim());
        Tamanos.add(TamanoPizza);
        Totales.add(Total);
        
        pedidoCounter++; // Incrementamos el contador de pedidos para el siguiente
       // 
        actualizarTabla();
        actualizarTotal();
    }//GEN-LAST:event_jButton_AgregarPedidoActionPerformed

    private void actualizarTabla() {
        DefaultTableModel model = (DefaultTableModel) jTable_Pedido.getModel();
        model.setRowCount(0); 

        for (int i = 0; i < NumeroPedidos.size(); i++) {
            model.addRow(new Object[]{
                NumeroPedidos.get(i),
                Nombres.get(i),
                Apellidos.get(i),
                Ingredientes.get(i),
                Tamanos.get(i),
                Totales.get(i)
            });
        }
    }

    private void actualizarTotal() {
        double totalGeneral = 0.0;
        for (Double total : Totales) {
            totalGeneral += total;
        }
        jLabel_MontoTotal.setText(String.valueOf(totalGeneral));
    }
    

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jButton_SalirActionPerformed

    private void jButton_EliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarPedidoActionPerformed
        // TODO add your handling code here:
    int selectedRow = jTable_Pedido.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un pedido para eliminar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        NumeroPedidos.remove(selectedRow);
        Nombres.remove(selectedRow);
        Apellidos.remove(selectedRow);
        Ingredientes.remove(selectedRow);
        Tamanos.remove(selectedRow);
        Totales.remove(selectedRow);

        actualizarTabla();
        actualizarTotal();
        
    }//GEN-LAST:event_jButton_EliminarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_TamañosPizza;
    private javax.swing.JButton jButton_AgregarPedido;
    private javax.swing.JButton jButton_EliminarPedido;
    private javax.swing.JButton jButton_GuardarPedido;
    private javax.swing.JButton jButton_LimpiarDatos;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JCheckBox jCheckBox_Ingrediente1;
    private javax.swing.JCheckBox jCheckBox_Ingrediente2;
    private javax.swing.JCheckBox jCheckBox_Ingrediente3;
    private javax.swing.JCheckBox jCheckBox_Ingrediente4;
    private javax.swing.JLabel jLabel_ApellidoCliente;
    private javax.swing.JLabel jLabel_DatosFecha;
    private javax.swing.JLabel jLabel_Fecha;
    private javax.swing.JLabel jLabel_IconPizzeria;
    private javax.swing.JLabel jLabel_MontoTotal;
    private javax.swing.JLabel jLabel_NombreCliente;
    private javax.swing.JLabel jLabel_NombrePizzeria;
    private javax.swing.JLabel jLabel_NumeroCliente;
    private javax.swing.JLabel jLabel_Total;
    private javax.swing.JPanel jPanel_DatosCliente;
    private javax.swing.JPanel jPanel_DetallesPedido;
    private javax.swing.JPanel jPanel_IngredientesPizza;
    private javax.swing.JPanel jPanel_Pedido;
    private javax.swing.JPanel jPanel_TamañoPizza;
    private javax.swing.JPanel jPanel_font;
    private javax.swing.JRadioButton jRadioButton_Tamaño1;
    private javax.swing.JRadioButton jRadioButton_Tamaño2;
    private javax.swing.JRadioButton jRadioButton_Tamaño3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_Pedido;
    private javax.swing.JTextField jTextField_InputApellido;
    private javax.swing.JTextField jTextField_InputNombre;
    private javax.swing.JTextField jTextField_NumeroCliente;
    // End of variables declaration//GEN-END:variables
}
